In [2]:
import numpy as np
import torch

In [4]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.5655, 0.0208, 0.8360],
        [0.1932, 0.9997, 0.6331],
        [0.7928, 0.2416, 0.9604],
        [0.3519, 0.4359, 0.4154]])

In [5]:
type(tensor)

torch.Tensor

In [6]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.56550664, 0.02081579, 0.83599246],
       [0.19321096, 0.99968356, 0.63311327],
       [0.7927647 , 0.24156451, 0.96042323],
       [0.35192204, 0.43594623, 0.41540915]], dtype=float32)

In [7]:
type(numpy_from_tensor)

numpy.ndarray

In [8]:
torch.is_tensor(tensor)

True

In [9]:
torch.is_tensor(numpy_from_tensor)

False

In [10]:
numpy_from_tensor[0, 0] = 100.0

numpy_from_tensor

array([[1.0000000e+02, 2.0815790e-02, 8.3599246e-01],
       [1.9321096e-01, 9.9968356e-01, 6.3311327e-01],
       [7.9276472e-01, 2.4156451e-01, 9.6042323e-01],
       [3.5192204e-01, 4.3594623e-01, 4.1540915e-01]], dtype=float32)

In [11]:
tensor

tensor([[1.0000e+02, 2.0816e-02, 8.3599e-01],
        [1.9321e-01, 9.9968e-01, 6.3311e-01],
        [7.9276e-01, 2.4156e-01, 9.6042e-01],
        [3.5192e-01, 4.3595e-01, 4.1541e-01]])

In [12]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0], 
                      [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [13]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [14]:
type(tensor_from_numpy)

torch.Tensor

In [15]:
torch.is_tensor(tensor_from_numpy)

True

In [16]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [17]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [18]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [19]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [20]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [21]:
tensor_from_array_one

tensor([4, 5])

In [22]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [23]:
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

In [24]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [25]:
tensor_from_array_two

tensor([2, 2])