In [1]:
import torch

In [2]:
initial_tensor = torch.rand(2,3)

initial_tensor

tensor([[0.3409, 0.1756, 0.2806],
        [0.0552, 0.3758, 0.0853]])

In [3]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [5]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [6]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [7]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [8]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [9]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [10]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [11]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [12]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1,tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [13]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [14]:
random_tensor[0, 1]

tensor(8.)

In [15]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [16]:
random_tensor.size()

torch.Size([3, 3])

In [17]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [18]:
resized_tensor.size()

torch.Size([9])

In [19]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [20]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [21]:
random_tensor.shape

torch.Size([3, 3])

In [22]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [23]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [25]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [26]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [27]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [28]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [29]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [30]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [31]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [32]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [33]:
add1 = rand1 + rand2
add1

tensor([[1.3745, 2.4919, 0.6121],
        [2.8413, 0.5747, 3.7351]])

In [34]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.3745, 2.4919, 0.6121],
        [2.8413, 0.5747, 3.7351]])

In [35]:
tensor = torch.Tensor([[-1, -2, -3], [1, 2, 3]])

In [36]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [37]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [38]:
tensor_clamp = torch.clamp(tensor, min= -0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [39]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [40]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [41]:
matrix = torch.Tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.Tensor([0, 1, 2])

In [42]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [43]:
another_matrix = torch.Tensor([[10, 30], [20, 0], [0, 50]])

In [44]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [48]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [ ]:
torch.argmin(matrix_mul, dim=1)