In [1]:
import torch

print(torch.__version__)

1.9.0


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.float64)

In [4]:
torch.get_default_dtype()

torch.float64

In [5]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
torch.is_tensor(tensor_arr)

True

In [7]:
torch.numel(tensor_arr)

6

In [8]:
tensor_uninitialized = torch.Tensor(2, 2)

In [9]:
tensor_uninitialized

tensor([[3.9525e-323,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [10]:
tensor_initialized = torch.rand(2, 2)

In [11]:
tensor_initialized

tensor([[0.4867, 0.5422],
        [0.9659, 0.7924]])

In [12]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [13]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

<ipython-input-13-13d21c85b74a>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

In [14]:
tensor_float = torch.ShortTensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

<ipython-input-14-e07008113a51>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_float = torch.ShortTensor([1.0, 2.0, 3.0]).type(torch.half)


tensor([1., 2., 3.], dtype=torch.float16)

In [15]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [16]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [17]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [18]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [20]:
i = torch.tensor([[0, 1, 1], [2, 2, 0]])

In [22]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

In [23]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [28]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)